# Generated by Django 3.2.9 on 2021-12-25 22:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('api_id', models.CharField(max_length=255)),
                ('kinds', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('categories', models.CharField(blank=True, max_length=255)),
                ('image_url', models.URLField(blank=True)),
                ('api_id', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='MyLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attractions', models.ManyToManyField(blank=True, related_name='my_locations', to='fantaland_app.Attraction')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_locations', to='fantaland_app.location')),
                ('restaurants', models.ManyToManyField(blank=True, related_name='my_locations', to='fantaland_app.Restaurant')),
                ('traveller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_locations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
