# Generated by Django 3.2.9 on 2021-12-26 03:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fantaland_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attraction',
            name='location',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, related_name='attractions', to='fantaland_app.location'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurant',
            name='location',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, related_name='restaurants', to='fantaland_app.location'),
            preserve_default=False,
        ),
    ]
