# Generated by Django 3.2.9 on 2021-12-26 04:06

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fantaland_app', '0002_auto_20211226_0347'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='mylocation',
            unique_together={('traveller', 'location')},
        ),
    ]
