# Generated by Django 3.2.9 on 2021-12-26 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantaland_app', '0004_auto_20211226_2346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attraction',
            name='api_id',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='api_id',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='attraction',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='location',
            unique_together={('lat', 'lon')},
        ),
        migrations.AlterUniqueTogether(
            name='restaurant',
            unique_together=set(),
        ),
    ]
